<?php

namespace Sio\SemiBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AcademieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AcademieRepository extends EntityRepository
{
	public function findIdAcadamie($academie) 
		{
			$em = $this -> getEntityManager();
			$query = $em -> createQuery("SELECT aca.id FROM SioSemiBundle:Academie aca WHERE aca.nom ='$academie'");
			return $query -> getResult();
		}
}
