<?php

namespace Sio\SemiBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AcademieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AcademieRepository extends EntityRepository
{
	public function findAllAcadamie() 
		{
			$em = $this -> getEntityManager();
			$query = $em -> createQuery("SELECT aca.nom FROM SioSemiBundle:Academie aca ");
			return $query -> getResult();
		}
}
