<?php

namespace Sio\SemiBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SeanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeanceRepository extends EntityRepository
{
	public function findAllSeance() 
		{
			$em = $this -> getEntityManager();
			$query = $em -> createQuery("SELECT sea FROM SioSemiBundle:Seance sea ");
			return $query -> getResult();
		}
		
	
}
